apiVersion: v1
kind: Service
metadata:
  name: check-my-ip-svc
spec:
  type: ClusterIP # The service only can be accessed from internal
  selector:
    app: check-my-ip
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080