name: "build-deploy"
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      context:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push: true
          tags: distucker/${{ inputs.app-name }}:${{ github.sha }}
  deploy:
    name: Deploy  App to GKE
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: get-gke-credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Set up GKE kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Update Image tags
        run: sed "s|distucker/${{inputs.app-name}}:image-tag|distucker/${{inputs.app-name}}:${{github.sha}}|" ./deployment/${{inputs.app-name}}-deployment.yaml 
      - name: Deploy to GKE
        run: kubectl apply -f ./deployment/${{inputs.app-name}}-deployment.yaml