name: "build and deployment"
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      context:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push: true
          tags: distucker/${{ inputs.app-name }}:${{ github.sha }}
  deploy:
    name: Deploy  App to GKE
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to GKE
        uses: google-github-actions/deploy-gke@v0.10.0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}
          manifests: ./deployment/${{ inputs.app-name }}-deployment.yaml
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        env:
          IMAGE: distucker/${{ inputs.app-name }}:${{ github.sha }}
