name: "CheckMyIP Deployment"
on:
  push:
    branches:
      - main
    paths:
      - 'CheckMyIP/*'

jobs:
  build-and-deployment:
    uses: ./.github/workflows/build-deployment.yaml
    secrets: inherit
    with:
      app-name: check-my-ip
