name: Go Unit Test
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - main
    paths:
      - 'CheckMyIP/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        working-directory: ./CheckMyIP
        run: go install .
      - name: Test with the Go CLI
        working-directory: ./CheckMyIP
        run: go test *.go -v
