name: Node Unit Test
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - main
    paths:
      - 'CheckMySite/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
        working-directory: ./CheckMySite
      - run: npm test
        working-directory: ./CheckMySite
